name: littlefish_feature_models
description: Shared domain models package for littlefish merchant app. Contains all common data models organized by domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  
  # Littlefish core dependencies
  littlefish_core: ^4.2.0
  littlefish_core_utils:
    path: ../../../littlefish_core_mono_repo/packages/utils/littlefish_core_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
